name: "CI - Plugin: Run Checks"

on:
  pull_request:
    paths:
      - "plugin/**"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/ci-plugin.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: make install

      - name: Run checks
        run: make checks

      - name: Run tests
        run: make test

      - name: Build package
        run: make build
